### ISSUE TITLE
data input/output

### ISSUE THREAD

**Issue by farrell236** [luukboulogne/stoic2021-baseline#2]
Hello,

When running process.py with multiple images in `test/images/ct`, I also get the following error:

```
RuntimeError: Multiple case prediction not supported with single-value output interfaces.
```

I'm not familiar with the `evalutils` library, do you know whats going wrong here?

Thanks!

**Comment by luukboulogne** [comment]
Hi Farrell,

Unfortunately it is not possible to run process.py with multiple images. On Grand Challenge, your Algorithm will run on each image individually.

Further explanation:
For the Leaderboard to read the output of your Algorithm, your Algorithm needs to implement the `Probability COVID-19` and `Probability Severe COVID-19` output interfaces (see https://grand-challenge.org/algorithms/interfaces/). To implement these interfaces, the output .json files (`/output/probability-severe-covid-19.json` and `/output/probability-covid-19.json`) contain only a single float value each, and have fixed paths. This makes it impossible to generate predictions for multiple cases.

**Comment by farrell236** [comment]
ahh ok, thanks!
